# Copyright (C) 2017 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>  


FROM selenium/standalone-chrome:3.4.0-chromium

USER root
COPY ./provision/docker/selenium.bashrc.j2 /root/.bashrc
RUN apt-get update && apt-get install -y python python-pip python-setuptools

COPY ./src/requirements-selenium.txt /tmp/requirements.txt
RUN pip install pip \
  && pip install -r /tmp/requirements.txt

RUN usermod -u 1000 seluser

WORKDIR /selenium
USER seluser

RUN sudo apt-get -y install wmaker
RUN /usr/bin/xscreensaver -no-splash & exec wmaker

RUN sudo apt-get update && sudo apt-get install -y x11vnc xvfb
RUN sudo mkdir -p $HOME/.vnc
RUN sudo x11vnc -storepasswd 12345 $HOME/.vnc/passwd
RUN sudo chown -R seluser:seluser $HOME/.vnc/

EXPOSE 5900
CMD ["x11vnc", "-forever", "-usepw", "-create"]